### ISSUE TITLE
Git pre-commit/pre-push hooks

### ISSUE THREAD

**Issue by UARTman** [objectionary/sodg#13]
Although we recommend in `README.MD` to run `cargo fmt` and `cargo clippy` before sending the pull request, it's easy to forget to do so. To deal with this problem, we can use the Git's in-built hook capabilities.

Git hooks allow you to run a script before commit or before push, and any error in the script will stop the proccess. Although it's impossible to add hooks through a repository (hooks are stored in `.git`), we can include a simple script that does so. Then, instead of remembering to run all the commands each time, the contributor needs to run a script one time after cloning the repo, and then the testing will be done automatically.

Do you thing we should do that, and if we do, should we use pre-commit or pre-push hooks?

**Comment by yegor256** [comment]
@UARTman good practice, but we tend not to do this, since it's personal. Each programmer must worry about their own dev environment. We don't have with this _anyhow_.
