### ISSUE TITLE
ops.rs:86-89: Let's implement this method. It has to find...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/sodg#2]
The puzzle `1-968ec83e` from #1 has to be resolved: 

https://github.com/objectionary/sot/blob/f7f8e1ed1cdae28e9922b0bbda4c568e87ba65a9/src/sot/ops.rs#L86-L89

The puzzle was created by @yegor256 on 04-Oct-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@levBagryansky please, try to help

**Comment by levBagryansky** [comment]
@yegor256 seems it's not actual now

**Comment by yegor256** [comment]
@levBagryansky indeed, it's expired
