### ISSUE TITLE
A number of structural issues

### ISSUE THREAD

**Issue by UARTman** [objectionary/sodg#26]
In the process of re-writing `Hex` I've found a number of structural issues in the codebase. Mostly, it's the API architecture not following Rust best practices.

For example, right now, the types and their implementations are in the different modules. For example, `Hex` is declared in the root module, while all its methods are in the `hex` module. 

The better way to do it would be to implement `Hex` in the `hex` module and use a `pub use crate::hex::Hex;` in the `lib.rs` to re-export it.

Another issue is disregard for traits and generic programming when creating APIs, such as writing a bunch of `from_` methods that use the `From` trait in an identical manner and implementing `from_str` not through the `FromStr` trait, but as a standalone method.

**Comment by yegor256** [comment]
@UARTman make a separate issue for each problem and then we fix them one by one. Don't group problems in one ticket.
