### ISSUE TITLE
Move struct declaration to the proper modules.

### ISSUE THREAD

**Issue by UARTman** [objectionary/sodg#28]
Right now, most of the structs are implemented in the root module (`lib.rs`), despite the fact their methods are implemented in other modules (like, say, `hex`). The only rationale I can think of for doing this is so that they are visible at the crate top level (i.e. `sodg::Hex`).

There is a more idiomatic way to do this. First, we declare the structure in its module (i.e. `Hex` in `hex`). The, in the `lib.rs` we write `pub use hex::Hex;` to re-export the struct at the top level. 

I propose we do that for all the structs declared in `lib.rs` which have method implementations in another module.

**Comment by yegor256** [comment]
@UARTman I agree, let's do it
