### ISSUE TITLE
find() with a closure

### ISSUE THREAD

**Issue by yegor256** [objectionary/sodg#31]
This is what I would like to be able to do with `Sodg.find()` function:

```rust
use sodg::Sodg;
let mut g = Sodg::empty();
g.add(0).unwrap();
g.add(1).unwrap();
g.bind(0, 1, "foo").unwrap();
let v = g.find(0, "bar", |v, a| "foo").unwrap();
assert_eq!(1, v);
```

The closure that I provided to `find` function expects two parameters: 1) the ID of the vertex where finding algorithm stopped because edge `"foo"` is absent (`v=0`), 2) the name of the edge not found (`a="bar"`). The closure returns an alternative name of the edge and the search algorithm continues from it.

**Comment by yegor256** [comment]
@UARTman can you please help?

**Comment by UARTman** [comment]
Sure. Let's check if I understand correctly what you want it to do.

It checks for "bar" in children, doesn't find it, then goes through the children, calling the closure on every one, until it finds "bar". Then it uses that edge and goes further.

**Comment by yegor256** [comment]
@UARTman not exactly. It checks for "bar" in children, doesn't find it. Then, it calls the closure giving it itself (0) and the name of the missing children ("bar"). The closure returns "foo". It finds "foo" in children and continues.

I made a mistake in the original description of the ticket. Now fixed.

**Comment by yegor256** [comment]
@UARTman let's make it even more convenient. Let the closure accept _three_ params: vertex ID, the head of the label, and the tail of the label. Say, label is `"a/bc.de"`. Here `"a"` is the head, while `"bc.de"` is the tail.

**Comment by yegor256** [comment]
@UARTman any progress?

**Comment by UARTman** [comment]
I have an implementation that seems to work in a separate function `find_with_closure`. Should I just replace `find` with the new function or leave `find` as-is?

After we figure out this, I'll have to improve a docstring a bit, and then it'll be ready for merge.

**Comment by yegor256** [comment]
@UARTman let's merge `find_with_closure` first

**Comment by yegor256** [comment]
@UARTman any good?

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.12`
