### ISSUE TITLE
avoid duplication in Sodg::merge()

### ISSUE THREAD

**Issue by yegor256** [objectionary/sodg#65]
Let's modify the function `Serge::merge`:

```
pub fn merge(&mut self, other: Sodg) -> Result<()>;
```

It should take all vertices from the `other` SODG and put them into the current one. 

What is important is that duplication must be avoided, using edges. For example, in the current SODG a vertex `ν1` is bound to `ν2` by the edge `"foo"`. In the `other` SODG the same vertex `ν1` is bound to `ν3` with an edge `"foo"`. The edge `ν3` should _not_ be created in the current SODG.

**Comment by yegor256** [comment]
@UARTman can you help please?

**Comment by l3r8yJ** [comment]
@yegor256 i can try to close it

**Comment by yegor256** [comment]
@l3r8yJ I'm already working on this one. please, pick something else

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.24`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.24`
